framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
        utf8: true

        default_uri: '%env(APP_DEFAULT_URI)%'
when@prod:
    framework:
        router:
            strict_requirements: null
